/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description [P12] login_anonymous(nickname)，以及 BE-G01 的 resume。
         *
         *     沒有密碼欄位、沒有 OAuth（守則 §3）。登入即建立一張名片 —— 帳號與名片
         *     是同一個東西，profiles 就是使用者表。
         *
         *     給 `resume_token` 則是拿回既有的名片，不建新的。**它不是驗證身分**：
         *     拿到 token 的人就是那張名片的人。這解掉的是「清掉 cookie 或換一台電腦
         *     就再也回不去」，不是「證明這個身分屬於我」——後者要帳號密碼，那會動到
         *     schema 與規格書 §9，是另一個決定。
         *
         *     給 `login_id` + `password` 則是**驗證身分**（L3）：帳號不存在與密碼錯誤
         *     回同一句話，不透露哪一個錯了。用 403 而不是 401 —— 401 在整合指南 §4 的
         *     約定是「導向登入畫面」，而使用者本來就在登入畫面上，導過去會變成迴圈；
         *     403 的約定是「顯示 detail，密碼錯則留在密碼框」，那正是這裡要的行為。
         */
        post: operations["login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description 建立一個帶帳號密碼的名片（L3，9/8 裁決）。
         *
         *     註冊完直接是登入狀態 —— 註冊後再叫人登入一次，是拿使用者的時間去補一個
         *     系統自己就能做的動作。
         *
         *     撞名由 profiles.login_id 的 unique 擋，不先查再寫（守則 §1 規則 4）：
         *     先查再寫在單機測試裡永遠是對的，兩個人同時註冊同一個帳號才會露出來。
         *
         *     這裡不做 email、不做驗證信、不做密碼重設 —— 沒有寄信管道，做出來的
         *     「忘記密碼」會是一條走不完的路。使用者忘記密碼就用 resume_token 回來，
         *     或重新註冊一個。
         */
        post: operations["register_api_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Profiles
         * @description [P17]。只做翻頁，不做搜尋與篩選（任務表明列）。
         *
         *     超過尾頁回空清單，不是 404 —— 翻到底是正常操作，不是錯誤。
         */
        get: operations["list_profiles_api_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Me
         * @description [P15]。未給的欄位不動。
         *
         *     長度上限交給資料庫的 check 擋（守則 §1 規則 3 與任務表 [P15]：禁止在
         *     應用層重複實作長度檢查）。因此超長會是 500 而不是 422 —— 這是刻意的，
         *     真正的規則只有一份，寫在 sql/001_schema.sql。
         */
        patch: operations["update_me_api_profiles_me_patch"];
        trace?: never;
    };
    "/api/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profiles__profile_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description [P20] 任務看板。過期的不出現。
         *
         *     只在查詢時過濾，不實作到期排程與提醒（守則 §3：貼文到期提醒、續期、
         *     自動下架排程已砍除）。「自動下架」因此是查詢的結果，不是背景工作 ——
         *     少了一個排程器，也少了一種會在半夜壞掉的東西。
         */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description [P19]。expires_at 用資料庫預設值（now() + 7 days），不在應用層算。
         */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description [P21]。
         */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/form-team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Form Team
         * @description [P33] 成軍。§6.1：status／room_template／password_hash 同一個交易內寫完。
         *
         *     分開寫的話，中間任何一步失敗都會留下 room_ready check 擋不住的中間狀態
         *     —— 不，其實 check 會擋住，這正是它存在的價值：即使這裡寫錯，資料庫也
         *     不會讓「成軍了但房間沒開」這件事發生。
         */
        post: operations["form_team_api_projects__project_id__form_team_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Project
         * @description [P35] 結案。§6.1：座位全數釋放、門從走廊移除。
         *
         *     **2026-09-08 P1 裁決（選項 A）：維持這個行為，改正文件。**
         *
         *     背景是規格書內部的矛盾：§4.1 說「專案結束時座位自動釋放」的機制是
         *     on delete cascade，但 cascade 只在刪除專案列時觸發，而 §6.1 的生命週期圖
         *     裡 closed 是專案**保留下來**的狀態 —— 專案還在，cascade 不會發生。
         *
         *     裁決保留的作法：同一個交易內把 status 改成 closed，並以**一句 delete**
         *     釋放座位。是集合操作，不是在 Python 裡逐筆迴圈，所以任務表 [P34] 的
         *     「不得在應用層逐筆刪除」仍然成立。
         *
         *     被否決的兩個選項與理由：
         *       · 結案即刪除專案列（讓 cascade 真的發生）—— 專案歷史隨之消失，
         *         前端的 BE-G22／FE-T（合作紀錄與聲譽）就永遠做不成了
         *       · 加 trigger —— 為了一句文件引入這個 repo 目前沒有的隱藏控制流
         *
         *     **代價（明寫在這裡，因為它不再由資料庫保證）：** 座位釋放是這一段程式的
         *     責任。刪掉下面那句 delete，沒有任何約束會擋，而測試會是唯一的守門員。
         */
        post: operations["close_project_api_projects__project_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/enter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enter Room
         * @description [P37]。§6.2：共享密碼，不做成員制。密碼錯回 403。
         *
         *     簽出的 token 有兩個用途：存進 session 給座位端點用，回傳給前端接在
         *     WebSocket 的 ?token= 上（附錄 A.1）。
         */
        post: operations["enter_room_api_projects__project_id__enter_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Seats
         * @description [P42]。座位滿即房間滿（§6.3），不需另寫容量判斷。
         *
         *     沒有釋放座位的端點 —— 已於 WBS v0.2 砍除（守則 §3）。
         */
        get: operations["list_seats_api_projects__project_id__seats_get"];
        put?: never;
        /**
         * Claim Seat
         * @description [P40] 認領座位。
         *
         *     沒有 SELECT，沒有應用層的鎖。直接 INSERT，讓 seats 的兩個約束說話：
         *       · primary key (project_id, seat_index) → 一格只能一人
         *       · unique     (project_id, user_id)     → 一人只能一格
         *     兩者都轉成 409（附錄 C）。
         *
         *     UniqueViolationError 同時涵蓋 PK 與 unique 衝突，因此用 constraint 名稱
         *     分辨是哪一種，好讓前端能給出不同的訊息。
         *
         *     ## 座位數上限為什麼寫成 INSERT ... SELECT ... WHERE
         *
         *     規格書 §6.3 要求「房間人數上限 = 座位數」，但這條約束跨 projects 與 seats
         *     兩張表，PostgreSQL 的 check 寫不出來，所以由 P1 裁決改在這裡擋。
         *
         *     看起來像是把「先查再寫」請回來了，其實不是 —— 關鍵在於查的是**哪張表**：
         *
         *       · 危險的先查再寫，查的是 seats：「這格有沒有人坐？」
         *         兩個人同時查都會得到「沒有」，然後兩個都寫進去
         *       · 這裡查的是 projects.seat_count：「這個房間有沒有第 7 格？」
         *         這個答案跟誰在跟你搶完全無關，成軍之後 seat_count 也不再變動
         *
         *     所以兩個不變式是正交的，加了容量檢查並沒有削弱競爭防護：
         *     同時搶 seat 1 的兩個人一樣會通過容量檢查、一樣在 PK 上撞、一樣只有一個
         *     成功。容量不足時則兩個都被擋，也是對的。
         *
         *     即使如此仍然寫成單一句 INSERT ... SELECT 而不是「先 fetchval 再 insert」，
         *     有兩個理由：成功路徑少一次來回；以及不留下一段長得像正確寫法的先查再寫，
         *     讓日後讀這個檔案的人不會照著它去改別的地方。
         */
        post: operations["claim_seat_api_projects__project_id__seats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description [P28]。主體條件寫在 WHERE 裡，不是取回來之後才過濾。
         *
         *     §3 的原則：即時內容空間限定，非即時內容全域可達 —— 對話隔音，收件匣
         *     不隔音。所以這裡同時撈寄件與收件，兩者都是「我的信」。
         */
        get: operations["list_messages_api_messages_get"];
        put?: never;
        /**
         * Send Message
         * @description [P27]。寄給自己由資料庫的 no_self_send check 擋下，不在這裡判斷。
         */
        post: operations["send_message_api_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rooms
         * @description 成軍中（active）的專案就是走廊上的門。
         *
         *     closed 的專案「門從走廊移除」（§6.1），因此這裡只查 active。
         */
        get: operations["list_rooms_api_rooms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EnterIn */
        EnterIn: {
            /** Password */
            password: string;
        };
        /**
         * EnterOut
         * @description §6.2：驗證通過後取得 room token，WS 握手時用（附錄 A.1）。
         */
        EnterOut: {
            /** Room Token */
            room_token: string;
        };
        /**
         * FormTeamIn
         * @description 成軍。§6.1：系統指派房間模板、發起人設定密碼，同一個動作完成。
         */
        FormTeamIn: {
            /** Password */
            password: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginIn
         * @description 規格書 §9：匿名登入，暱稱即可，不走 OAuth。沒有密碼欄位。
         *
         *     兩種模式，剛好給一個：
         *
         *     - `nickname` —— 建立一張新名片
         *     - `resume_token` —— 拿回既有的名片。它就是 `ProfileOut.id`，登入時已經
         *       回給前端了，所以不必為它新增任何欄位或端點
         *
         *     **`resume_token` 不是密碼。** 拿到它的人就是那張名片的人。它解的是「同一
         *     個人換裝置、或清掉 cookie 之後回得去」（BE-G01），不是「證明這個身分屬於
         *     我」。要後者得做帳號密碼，那會動到 sql/001_schema.sql 與規格書 §9，是另一
         *     個決定。
         *
         *     - `login_id` + `password` —— 帳號密碼登入（L3，9/8 裁決）。這一組才是**驗證
         *       身分**：它證明這個身分屬於你，前兩種都不證明
         *
         *     剛好給一組，多給或少給都是 422。刻意不做「都給就以某一邊為準」——
         *     那是在互相打架的意圖裡自己挑一邊信，而呼叫端不會知道被挑掉的是哪一個。
         *
         *     三種模式並存不是折衷，是三種不同的入場方式：發表日現場走匿名（§9，不能
         *     卡在註冊），一般使用者走帳號密碼，換裝置的人走 resume_token。
         */
        LoginIn: {
            /** Nickname */
            nickname?: string | null;
            /** Resume Token */
            resume_token?: string | null;
            /** Login Id */
            login_id?: string | null;
            /** Password */
            password?: string | null;
        };
        /** MessageCreate */
        MessageCreate: {
            /**
             * Recipient Id
             * Format: uuid
             */
            recipient_id: string;
            /** Body */
            body: string;
        };
        /**
         * MessageOut
         * @description immutable（§4.2）—— 沒有對應的 update / delete model，因為沒有那些端點。
         */
        MessageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Sender Id
             * Format: uuid
             */
            sender_id: string;
            /**
             * Recipient Id
             * Format: uuid
             */
            recipient_id: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Read At */
            read_at: string | null;
        };
        /** ProfileOut */
        ProfileOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
            /** Avatar Id */
            avatar_id: number;
            /** Skills */
            skills: string[];
            /** Hours Per Week */
            hours_per_week: number | null;
            /** Bio */
            bio: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProfileUpdate
         * @description PATCH /api/profiles/me。未給的欄位不動。
         */
        ProfileUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Avatar Id */
            avatar_id?: number | null;
            /** Skills */
            skills?: string[] | null;
            /** Hours Per Week */
            hours_per_week?: number | null;
            /** Bio */
            bio?: string | null;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Title */
            title: string;
            /** Body */
            body: string;
            /**
             * Needed Skills
             * @default []
             */
            needed_skills: string[];
            /**
             * Seat Count
             * @default 4
             */
            seat_count: number;
        };
        /**
         * ProjectOut
         * @description 刻意不含 password_hash。房間密碼是共享密碼，任何情況下都不回給客戶端。
         */
        ProjectOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Needed Skills */
            needed_skills: string[];
            status: components["schemas"]["ProjectStatus"];
            /** Room Template */
            room_template: number | null;
            /** Seat Count */
            seat_count: number;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProjectStatus
         * @description 對應 sql 的 project_status enum。
         * @enum {string}
         */
        ProjectStatus: "recruiting" | "active" | "closed";
        /**
         * RegisterIn
         * @description 註冊一個帳號（L3）。
         *
         *     `login_id` 是帳號，`nickname` 是世界裡顯示的名字 —— 兩者刻意分開：
         *     `display_name` 沒有唯一約束而且改得動，拿它當帳號的話，改名就等於換帳號。
         *
         *     `login_id` 的長度規則寫在 sql/001_schema.sql 的 check，這裡不重複
         *     （守則 §1 規則 3）。密碼長度是唯一的例外：**明文不會進資料庫**，
         *     SQL 無從驗起，所以它只能寫在這裡 —— 這不是「兩邊各寫一份」。
         */
        RegisterIn: {
            /** Login Id */
            login_id: string;
            /** Password */
            password: string;
            /** Nickname */
            nickname: string;
        };
        /**
         * RoomDoorOut
         * @description 全案唯一合併兩層的回應（附錄 B ★）。
         *
         *     title 來自 PostgreSQL，online_count 來自即時層的記憶體。兩層跑在同一個
         *     process，所以這只是一次函式呼叫 —— 但它是兩層唯一的接觸點，日後出問題
         *     時第一個看它。
         */
        RoomDoorOut: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Title */
            title: string;
            /** Online Count */
            online_count: number;
        };
        /** SeatClaim */
        SeatClaim: {
            /** Seat Index */
            seat_index: number;
            /**
             * Desk Template
             * @default 0
             */
            desk_template: number;
        };
        /** SeatOut */
        SeatOut: {
            /** Seat Index */
            seat_index: number;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Desk Template */
            desk_template: number;
            /**
             * Claimed At
             * Format: date-time
             */
            claimed_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    list_profiles_api_profiles_get: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_api_profiles_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profiles__profile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProjectStatus"];
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    form_team_api_projects__project_id__form_team_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormTeamIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_project_api_projects__project_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enter_room_api_projects__project_id__enter_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_seats_api_projects__project_id__seats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeatOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_seat_api_projects__project_id__seats_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeatClaim"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeatOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_messages_get: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rooms_api_rooms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomDoorOut"][];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
